version: 2
jobs:
  make_dependencies:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
       name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
       command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - persist_to_workspace:
        root: ~/code
        paths:
        - ./*
  lint:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    parallelism: 1
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Lint
        command: ./gradlew lint
    - store_artifacts:
        path: app/build/reports
        destination: reports
  import_fabric_properties:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    parallelism: 1
    steps:
    - attach_workspace:
        at: ~/code/app
    - run:
        name: Import Properties
        command: echo -e "apiSecret=${FABRIC_API_SECRET}\napiKey=${FABRIC_API_KEY}" >> ~/code/app/fabric.properties
    - persist_to_workspace:
        root: ~/code
        paths:
        - app/fabric.properties
  build_app:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    parallelism: 1
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Build
        command: ./gradlew assembleRelease
    - store_artifacts:
        path: app/build/outputs/apk/
        destination: apks
    - persist_to_workspace:
        root: ~/code
        paths:
        - ./*
  deploy_fabric:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    parallelism: 1
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - deploy:
        name: Deploy Fabric
        command: ./gradlew crashlyticsUploadDistributionRelease

workflows:
  version: 2
  build:
    jobs:
    - make_dependencies
    - lint:
        requires:
        - make_dependencies
    - build_app:
        requires:
        - make_dependencies
        - lint
    - import_fabric_properties:
        filters:
          branches:
            only: master
    - deploy_fabric:
        requires:
        - build_app
        - import_fabric_properties
        filters:
          branches:
            only: master